version: '3.8'

services:
  web:
    build: ./application/web
    command: python manage.py run -h 0.0.0.0
    volumes:
      - ./application/web/:/usr/src/ussd_app/
    ports:
      - 5000:5000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  redis:
    image: redis:alpine
  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=tafuta_nyumba
      - POSTGRES_PASSWORD=tafuta_nyumba
      - POSTGRES_DB=tafuta_nyumba_dev
volumes:
  postgres_data: