version: '3.8'

services:
  web:
    build:
      context: ./application/web
      dockerfile: Dockerfile.prod
    command: gunicorn --bind 0.0.0.0:5000 manage:app
    volumes:
      - static_volume:/home/ussd_app/web/app/static
      - media_volume:/home/ussd_app/web/app/media
    expose:
      - 5000
    env_file:
      - ./.env.prod
    depends_on:
      - db 
  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db
  
  nginx:
    build: ./application/nginx
    volumes:
      - static_volume:/home/ussd_app/web/app/static
      - media_volume:/home/ussd_app/web/app/media
    ports:
      - 1337:80
    depends_on:
      - web

volumes:
  postgres_data_prod:
  static_volume:
  media_volume:
  
