houses = {
    "1": "Single rooms",
    "2": "Double rooms",
    "3": "Bedsitter",
    "4": "One Bedrooms",
    "5": "Two Bedrooms",
    "6": "Three Bedrooms",
    "11": "Single rooms",
    "12": "Double rooms",
    "13": "Bedsitter",
    "14": "One Bedrooms",
    "15": "Two Bedrooms",
    "16": "Three Bedrooms",
    "10": "Bedsitter",
    "20": "One Bedrooms",
    "30": "Two Bedrooms",
    "40": "Three Bedrooms",
    "50": "Bedsitter",
    "60": "One Bedrooms",
    "70": "Two Bedrooms",
    "80": "Three Bedrooms",
}
