"""empty message

Revision ID: 03ad2ea89662
Revises: 707cca1dd580
Create Date: 2022-02-10 12:31:08.953352

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03ad2ea89662'
down_revision = '707cca1dd580'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('business_premises', schema=None) as batch_op:
        batch_op.add_column(sa.Column('photo', sa.String(length=254), nullable=True))

    with op.batch_alter_table('hostels', schema=None) as batch_op:
        batch_op.add_column(sa.Column('photo', sa.String(length=254), nullable=True))

    with op.batch_alter_table('houses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('photo', sa.String(length=254), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('houses', schema=None) as batch_op:
        batch_op.drop_column('photo')

    with op.batch_alter_table('hostels', schema=None) as batch_op:
        batch_op.drop_column('photo')

    with op.batch_alter_table('business_premises', schema=None) as batch_op:
        batch_op.drop_column('photo')

    # ### end Alembic commands ###
