"""empty message

Revision ID: 4779a0bb030e
Revises: af84f3c3fbe1
Create Date: 2022-03-15 09:02:43.443908

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4779a0bb030e'
down_revision = 'af84f3c3fbe1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('business_premises', schema=None) as batch_op:
        batch_op.drop_index('ix_business_premises_photo')

    with op.batch_alter_table('hostels', schema=None) as batch_op:
        batch_op.drop_column('photo')

    with op.batch_alter_table('houses', schema=None) as batch_op:
        batch_op.drop_index('ix_houses_image')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('houses', schema=None) as batch_op:
        batch_op.create_index('ix_houses_image', ['image'], unique=False)

    with op.batch_alter_table('hostels', schema=None) as batch_op:
        batch_op.add_column(sa.Column('photo', sa.VARCHAR(length=254), autoincrement=False, nullable=True))

    with op.batch_alter_table('business_premises', schema=None) as batch_op:
        batch_op.create_index('ix_business_premises_photo', ['photo'], unique=False)

    # ### end Alembic commands ###
