"""empty message

Revision ID: 4c410d1bd1cb
Revises: a4b9127edd37
Create Date: 2022-04-04 11:40:36.572063

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4c410d1bd1cb'
down_revision = 'a4b9127edd37'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index('ix_user_email')
        batch_op.drop_index('ix_user_name')

    op.drop_table('user')
    with op.batch_alter_table('business_assets', schema=None) as batch_op:
        batch_op.drop_constraint('business_assets_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users_table', ['user_id'], ['id'])

    with op.batch_alter_table('hostel_assets', schema=None) as batch_op:
        batch_op.drop_constraint('hostel_assets_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users_table', ['user_id'], ['id'], ondelete='cascade')

    with op.batch_alter_table('house_assets', schema=None) as batch_op:
        batch_op.drop_constraint('house_assets_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users_table', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('house_assets', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('house_assets_user_id_fkey', 'user', ['user_id'], ['id'])

    with op.batch_alter_table('hostel_assets', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('hostel_assets_user_id_fkey', 'user', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('business_assets', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('business_assets_user_id_fkey', 'user', ['user_id'], ['id'])

    op.create_table('user',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(length=40), autoincrement=False, nullable=True),
    sa.Column('created_on', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('profile_pic', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('unique_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='user_pkey')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index('ix_user_name', ['name'], unique=False)
        batch_op.create_index('ix_user_email', ['email'], unique=False)

    # ### end Alembic commands ###
