"""empty message

Revision ID: 5150530c57c8
Revises: 64e41f291ad7
Create Date: 2022-03-15 16:35:32.104842

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5150530c57c8'
down_revision = '64e41f291ad7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hostels', schema=None) as batch_op:
        batch_op.add_column(sa.Column('photo', sa.String(), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('photo', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('photo')

    with op.batch_alter_table('hostels', schema=None) as batch_op:
        batch_op.drop_column('photo')

    # ### end Alembic commands ###
