"""empty message

Revision ID: 6dfb1eb1723b
Revises: 4c410d1bd1cb
Create Date: 2022-04-04 11:52:07.184958

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6dfb1eb1723b'
down_revision = '4c410d1bd1cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users_table', schema=None) as batch_op:
        batch_op.drop_index('ix_users_table_email')
        batch_op.drop_index('ix_users_table_name')

    op.drop_table('users_table')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users_table',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('unique_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('profile_pic', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_on', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='users_table_pkey')
    )
    with op.batch_alter_table('users_table', schema=None) as batch_op:
        batch_op.create_index('ix_users_table_name', ['name'], unique=False)
        batch_op.create_index('ix_users_table_email', ['email'], unique=False)

    # ### end Alembic commands ###
