"""empty message

Revision ID: 6e1cb143699f
Revises: b52c001dbd44
Create Date: 2022-03-24 11:46:14.198004

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e1cb143699f'
down_revision = 'b52c001dbd44'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hostels', schema=None) as batch_op:
        batch_op.add_column(sa.Column('listing_status', sa.Enum('rent_out', 'sale', name='listingstatus'), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hostels', schema=None) as batch_op:
        batch_op.drop_column('listing_status')

    # ### end Alembic commands ###
