"""empty message

Revision ID: a681c666e077
Revises: 6e1cb143699f
Create Date: 2022-03-28 10:37:13.896538

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a681c666e077'
down_revision = '6e1cb143699f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hostel_assets', schema=None) as batch_op:
        batch_op.drop_constraint('hostel_assets_user_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('hostel_assets_hostels_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'], ondelete='cascade')
        batch_op.create_foreign_key(None, 'hostels', ['hostels_id'], ['id'], ondelete='cascade')

    with op.batch_alter_table('hostels', schema=None) as batch_op:
        batch_op.add_column(sa.Column('listing_status', sa.Enum('rent_out', 'sale', name='listingstatus'), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hostels', schema=None) as batch_op:
        batch_op.drop_column('listing_status')

    with op.batch_alter_table('hostel_assets', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('hostel_assets_hostels_id_fkey', 'hostels', ['hostels_id'], ['id'])
        batch_op.create_foreign_key('hostel_assets_user_id_fkey', 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###
