"""empty message

Revision ID: af84f3c3fbe1
Revises: 477a4f953b30
Create Date: 2022-03-14 10:04:54.012362

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af84f3c3fbe1'
down_revision = '477a4f953b30'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment_plan', schema=None) as batch_op:
        batch_op.add_column(sa.Column('latitude', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('longitude', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('type_of_property', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('units', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('price', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('plan', sa.Enum('weekly', 'monthly', 'annually', name='paymentplanstatus'), nullable=True))
        batch_op.add_column(sa.Column('amount', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('service_type', sa.Enum('rent_out', 'sell', name='servicetypestatus'), nullable=True))
        batch_op.add_column(sa.Column('date', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment_plan', schema=None) as batch_op:
        batch_op.drop_column('date')
        batch_op.drop_column('service_type')
        batch_op.drop_column('amount')
        batch_op.drop_column('plan')
        batch_op.drop_column('price')
        batch_op.drop_column('units')
        batch_op.drop_column('type_of_property')
        batch_op.drop_column('longitude')
        batch_op.drop_column('latitude')

    # ### end Alembic commands ###
