"""empty message

Revision ID: b52c001dbd44
Revises: 80d8569b6304
Create Date: 2022-03-24 08:22:08.038974

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b52c001dbd44'
down_revision = '80d8569b6304'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_unique_id', sa.String(length=254), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('user_unique_id')

    # ### end Alembic commands ###
