"""empty message

Revision ID: c464a71656d8
Revises: fdf4cfff805a
Create Date: 2022-02-10 22:29:48.640669

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c464a71656d8'
down_revision = 'fdf4cfff805a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('business_premises', schema=None) as batch_op:
        batch_op.add_column(sa.Column('photo', sa.String(), nullable=True))

    with op.batch_alter_table('houses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('houses', schema=None) as batch_op:
        batch_op.drop_column('image')

    with op.batch_alter_table('business_premises', schema=None) as batch_op:
        batch_op.drop_column('photo')

    # ### end Alembic commands ###
