"""empty message

Revision ID: e617ad776c8c
Revises: 2ca0eb953767
Create Date: 2022-03-30 09:35:35.107142

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e617ad776c8c'
down_revision = '2ca0eb953767'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('business_assets', schema=None) as batch_op:
        batch_op.drop_constraint('business_assets_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['unique_id'])

    with op.batch_alter_table('hostel_assets', schema=None) as batch_op:
        batch_op.drop_constraint('hostel_assets_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['unique_id'], ondelete='cascade')

    with op.batch_alter_table('house_assets', schema=None) as batch_op:
        batch_op.drop_constraint('house_assets_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['unique_id'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unique_id', sa.String(), autoincrement=False, nullable=False))
        batch_op.drop_column('id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
        batch_op.drop_column('unique_id')

    with op.batch_alter_table('house_assets', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('house_assets_user_id_fkey', 'user', ['user_id'], ['id'])

    with op.batch_alter_table('hostel_assets', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('hostel_assets_user_id_fkey', 'user', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('business_assets', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('business_assets_user_id_fkey', 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###
