"""empty message

Revision ID: fdf4cfff805a
Revises: 03ad2ea89662
Create Date: 2022-02-10 17:29:55.695291

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fdf4cfff805a'
down_revision = '03ad2ea89662'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('business_premises', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_business_premises_photo'), ['photo'], unique=False)

    with op.batch_alter_table('houses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.String(length=254), nullable=True))
        batch_op.create_index(batch_op.f('ix_houses_image'), ['image'], unique=False)
        batch_op.drop_column('photo')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('houses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('photo', sa.VARCHAR(length=254), autoincrement=False, nullable=True))
        batch_op.drop_index(batch_op.f('ix_houses_image'))
        batch_op.drop_column('image')

    with op.batch_alter_table('business_premises', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_business_premises_photo'))

    # ### end Alembic commands ###
