types_of_business_premises = {
    "1": "Kiosk/Kibanda",
    "2": "Shops",
    "3": "Office Space",
    "4": "Go-Downs",
    "5": "Kiosk/Kibanda",
    "6": "Shops",
    "7": "Office Space",
    "8": "Go-Downs",
    "10": "Kiosk/Kibanda",
    "20": "Shops",
    "30": "Office Space",
    "40": "Go-Downs",
    "50": "Kiosk/Kibanda",
    "60": "Shops",
    "70": "Office Space",
    "80": "Go-Downs",
}
